#!/bin/bash

process="$1"
cmd=$2

if ps ax | grep -v -e grep -e keepalive | grep "$process" > /dev/null
then
#	echo "keepalive: process $1 found, doing nothing"
#	echo "grep output:"
#	echo "$(ps ax | grep -v grep | grep "$process")"
	exit
else
	echo "keepalive: process $1 not found! running:"
	echo "\$ $cmd"
	$cmd &
fi

exit
